name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  container:
   image: google/dart:latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

 
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
   steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '2.8.0'
         channel: 'stable'
      - run: flutter --version
